[package]
name = "bevy1-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_easings = "0.4.1"
bevy_pixel_camera = "0.1.1"
bevy_rapier2d = "0.11.0"
benimator = "0.3.1"
big-brain = "0.8.0"
