[package]
name = "bevy1-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_easings = "0.4.1"
bevy_tilemap = "0.4.0"
bevy_loading = "0.1.2"
bevy_rapier2d = { version = "0.11.0", features = [ "simd-nightly" ] }
benimator = "0.3.1"
big-brain = "0.8.0"
itertools = "0.10.3"
noise = "0.7.0"
rand = "0.8.4"
rand_pcg = "0.3.1"
toodee = "0.3.0"


# Enable optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Maybe also enable only a small amount of optimization for our code:
[profile.dev]
opt-level = 1